// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';

//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwF0vUf9QYfEQds0wEe5kWOjZ2-qJvElA',
    appId: '1:503086710440:web:500a3190b4d1f9695ccc9d',
    messagingSenderId: '503086710440',
    projectId: 'store23-7b935',
    authDomain: 'store23-7b935.firebaseapp.com',
    storageBucket: 'store23-7b935.appspot.com',
    measurementId: 'G-50GDREHWP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ndUoOWzsdKhkSNFjl9QlRK5IwEsYT84',
    appId: '1:503086710440:android:f7f5e5d7c683b5725ccc9d',
    messagingSenderId: '503086710440',
    projectId: 'store23-7b935',
    storageBucket: 'store23-7b935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCJDGcERkW_4e-uOrhdRsQttgk-ogPsmY',
    appId: '1:503086710440:ios:ac3a0b6c8b9626ee5ccc9d',
    messagingSenderId: '503086710440',
    projectId: 'store23-7b935',
    storageBucket: 'store23-7b935.appspot.com',
    iosClientId: '503086710440-j1g4v3d0fmqp3i8b8d9185kq87kdoegp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCJDGcERkW_4e-uOrhdRsQttgk-ogPsmY',
    appId: '1:503086710440:ios:ac3a0b6c8b9626ee5ccc9d',
    messagingSenderId: '503086710440',
    projectId: 'store23-7b935',
    storageBucket: 'store23-7b935.appspot.com',
    iosClientId: '503086710440-j1g4v3d0fmqp3i8b8d9185kq87kdoegp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopFlutter',
  );
}
